### ISSUE TITLE
RFE: add piwik setup base URL / ability to modify the GA entry description

### ISSUE THREAD

**Issue by MagicFab** [sgiehl/piwik-plugin-GoogleAuthenticator#1]
When using an application such as [Google Authenticator on Android](https://f-droid.org/wiki/page/com.google.android.apps.authenticator2), scanning the code generated when configuring an account to use 2FA will add an entry with a description consisting only of the username.

It would be useful to add the website base URL in addition to the user alias and make this an editable description, for example: "website.com | useralias" before secret/QR code generation. This would prevent confusion in cases the same alias is used in several different Piwik setups.

**Comment by sgiehl** [comment]
Make that editable, is something I already had on my todo list for future versions. The Piwik url should already be in the title.
