### ISSUE TITLE
Plugin Download Appears Empty...

### ISSUE THREAD

**Issue by IberoMedia** [sgiehl/piwik-plugin-GoogleAuthenticator#14]
Hello,

I downloaded 2 Step Authentication Plugin for Piwik but when I open the zip there is nothing. 

I am using Windows 7 OS. 

I downloaded from https://plugins.piwik.org/GoogleAuthenticator 

Is it just me, or is the zip file actually empty?

Thank you

**Comment by sgiehl** [comment]
Thanks for the information. That seems to be a general problem on the Piwik page. All downloadable plugin zips seems to be invalid. I'll ping the right person to fix it...

**Comment by sgiehl** [comment]
Note: This seems to be a known issue on Windows. See https://github.com/piwik/piwik/issues/6538
