### ISSUE TITLE
Incompatible to newes Piwik Version 2.16.3

### ISSUE THREAD

**Issue by Der-K-2000** [sgiehl/piwik-plugin-GoogleAuthenticator#15]
> " Das Plugin GoogleAuthenticator ist nicht kompatibel mit Piwik 2.16.3."

Can you please fix it?

**Comment by mattab** [comment]
@theBear did you upgrade the plugin using the "Update" mechanism within Piwik itself? or did you manually upgrade the plugin?

**Comment by Der-K-2000** [comment]
I manually upgraded the new version on a http-installation, which leads to this fail. On a different (but https-installation), where I used the internal Update, it still works and it shows no error.

**Comment by sgiehl** [comment]
I'm not able to reproduce that. On my local Piwik (2.16.3) the plugin is running fine.
Is the incompatibility also shown in plugin admin, or are you able to (de-)activate it there?

**Comment by Der-K-2000** [comment]
It was automatically deactivated. I deinstalled it, re-installed it and now it works (without any new installation by google authentificator, the old settings are working). Weird. Thanks for replying anyway!
