### ISSUE TITLE
Not compatible with 3.0

### ISSUE THREAD

**Issue by pokrface** [sgiehl/piwik-plugin-GoogleAuthenticator#17]
Plugin has broken my 3.0 install and I can't uninstall it.

Error I get when attempting to log in:
```
2016/12/24 12:09:40 [error] 1324#1324: *106919 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Access level to Piwik\Plugins\GoogleAuthenticator\Controller::configureView() must be protected (as in class Piwik\Plugins\Login\Controller) or weaker in /var/www-piwik/plugins/GoogleAuthenticator/Controller.php on line 23" while reading response header from upstream, client: 127.0.0.1, server: analytics2.bigdinosaur.org, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "redacted"
```

When I remove the entries for GoogleAuthenticator from the [Plugins] and [PluginsInstalled] sections of `config.php.ini` and try to log in, I get this:

```
Authentication object cannot be found in the container. Maybe the Login plugin is not activated? 
You can activate the plugin by adding:
Plugins[] = Login
under the [Plugins] section in your config/config.ini.php
```

What the hell do I have to do to get this uninstalled so I can log in and use Piwik again? Extremely frustrated and angry.

edit - Fixed the issue by doing exactly what the second error message said—the Login plugin was not active (presumably because the GA plugin extends and replaces it), so I added it to the [Plugins] section.

Pretty hairy fix for a novice, though. Wish this failed in a more easily recoverable way.

**Comment by sgiehl** [comment]
Just released a new version that should work with Piwik 3.
