### ISSUE TITLE
Initial setup can not be completed

### ISSUE THREAD

**Issue by KaanErturk** [sgiehl/piwik-plugin-GoogleAuthenticator#18]
Thanks for updating the plugin for Piwik 3.0.0.

However I can't really use the plugin as the initial setup can't be completed. I scan the QR code, enter the 6-digit code and click on `Proceed`, but the page refreshes and a new secret is created. I then have to rescan the QR code then same steps and same result.

I did use this plugin in Piwik 2.17.x and it was working fine. I'm pretty sure I'm following the right steps but feel free to ask me to follow specific steps and/or send logs.

**Comment by sgiehl** [comment]
Thanks for the report. I'll try to reproduce that now...

**Comment by KaanErturk** [comment]
It's a fresh install btw, not an upgrade from 2.17.x.

**Comment by sgiehl** [comment]
I'm able to reproduce... working on a fix

**Comment by sgiehl** [comment]
Just released 3.0.1, which should fix the issue. Could you please test and confirm?

**Comment by KaanErturk** [comment]
All good now; managed to complete the setup and login with a 6-digit code.

Thanks for the quick fix.
