### ISSUE TITLE
Réinstalling GA after Piwik 3.0 : ask code but not installed in smartphone

### ISSUE THREAD

**Issue by Draky50110** [sgiehl/piwik-plugin-GoogleAuthenticator#19]
Hello.

I'm having a big trouble with this plugin.

I once used it with Piwik 2.x but had to disable it with Piwik 3.x.

I also deleted the authentification code in my smartphone 2FA app.

Then when the author made this plugin compatible with Piwik 3.x, i reactivated it but once activated it directly asks me with an app code, that I can't give because not more code in my 2FA app.

How can I use this plugin now ?

Thanks.

**Comment by sgiehl** [comment]
Sorry for the delay. You may need to remove the settings for your user in the database. 
piwik_option table; option_name is GoogleAuthenticator.username
Afterwards you should be able to active and enable it for your account again.
