### ISSUE TITLE
Don't ask for GA secret in the same "password" field

### ISSUE THREAD

**Issue by MagicFab** [sgiehl/piwik-plugin-GoogleAuthenticator#2]
The current implementation of this plugin asks the normal password credentials, then shows another identical login screen this time expecting 2FA secret but still asking for username and password (unless I've misunderstood this). Access is granted when the same username is entered, then the 2FA secret is entered in the password field.

It would be more intuitive not to ask for the username again and to identifiy the field to fill as "Secret" or "2FA secret", "Google authenticator" or else, while doing so in the same initial login screen.

**Edit** when using a password manager the second field is already filled and the "auth-code" background text indicating such value is needed (and not the usual password) is overwritten.

**Comment by sgiehl** [comment]
The username on the second screen is prefilled and readonly. So there shouldn't be a need to type that.
I'll check how to prevent the auth-code field to get filled by password managers

**Comment by sgiehl** [comment]
Should be fixed. If not, please reopen
