### ISSUE TITLE
Enabling : no QR code ?

### ISSUE THREAD

**Issue by Draky50110** [sgiehl/piwik-plugin-GoogleAuthenticator#20]
Hello.

Thanks to your help, I enabled it again, but on enable, it tells me to scan QR Code but... nothing is shown :/

![screenshot](https://cloud.githubusercontent.com/assets/1558487/22537558/db805008-e90b-11e6-9d9d-4327e835c9c3.png)

**Comment by sgiehl** [comment]
Any failing requests spotted in your browser's dev tools?

**Comment by Draky50110** [comment]
Solved.
Not all is ok when activating.
Maybe a browser cache problem ?

Thanks anyway for helping and providing this plugin :)
