### ISSUE TITLE
Token not usable with Two Factor Authentication

### ISSUE THREAD

**Issue by christianhauff** [sgiehl/piwik-plugin-GoogleAuthenticator#22]
After activating the 2FA-Plugin, the auth-token is not usable anymore. For the Reporting API, I did the workaround by creating a readonly-user, but for tracking with the PHP-API, there are several functions that only work with the auth_token, e.g. setIP! I think the token is especially for applications that are integrated permanently and therefore don't need 2FA. Is there a way to use the auth_token despite activated 2FA?

**Comment by sgiehl** [comment]
When using PHP you can generate the actual auth_code and send it with the URL as described in the README. The is currently no other way.
