### ISSUE TITLE
How to reset plugin?

### ISSUE THREAD

**Issue by brownsugar** [sgiehl/piwik-plugin-GoogleAuthenticator#25]
I just reset my phone and can't get auth code, so I deactivated plugin from console, then I tried to remove and reinstall this plugin, but every time I active this, I will be logged out and asked to enter auth code.
Is there any way to reset and get new setting on my phone?

**Comment by sgiehl** [comment]
You may need to remove the settings for your user in the database.
piwik_option table; option_name is GoogleAuthenticator.username
Afterwards you should be able to activate and enable it for your account again.
