### ISSUE TITLE
I want to develop a login plugin with openid, and do you have any advice or some references? It will be grateful for me if you can give me some advice！thanks！

### ISSUE THREAD

**Issue by wei1215583760** [sgiehl/piwik-plugin-GoogleAuthenticator#26]
I am a new developer using piwik and want to develop a login plugin with openid to replace the authentication method now. Can you give me some advice?

**Comment by sgiehl** [comment]
Feel free to have a look at this plugin and use it a base for a new login plugin. But I'm not able to give you any global advice how to build a new login plugin. If you have specific questions it might be easier to answer.
