### ISSUE TITLE
Lost phone, tried to reset 2FA, now plugin appears broken w/no QR or secret showing

### ISSUE THREAD

**Issue by pokrface** [sgiehl/piwik-plugin-GoogleAuthenticator#27]
My phone was damaged and replaced, so I'm going through the painful process of setting 2FA back up on everything.

I'm running piwik 3.2.1 and Google Authenticator plugin 3.0.2.

1) I removed the GA plugin from the active plugin list in config.ini.php and replaced it with the Login plugin. This enabled me to successfully log in.

2) When I reenable the GA plugin, I'm immediately prompted for a 2FA code. Obviously I can't give it one.

3) So I re-disable the 2FA plugin and attempted to follow the procedure [here](https://github.com/sgiehl/piwik-plugin-GoogleAuthenticator/issues/12), but there's no `GoogleAuthenticator.username` row. There IS, however, a `GoogleAuthentication.username` row (authentication, not authenticator), which I deleted.

4) Now I can activate the plugin without being prompted for 2FA, and I see a "Setup Google Authenticator" prompt ([image](https://i.imgur.com/RImlynR.png)).

5) However, when I click it expecting to get a QR code, I don't. Instead, I get a message about a QR code and secret but no code ([image](https://i.imgur.com/pzDbpTh.png)).

6) Clicking "Proceed" does nothing. The same page is redisplayed again.

7) Completely uninstalling the plugin and reinstalling leads to the exact same behavior.

Any suggestions on how to get this fixed would be very helpful. Happy to do database surgery if needed.

**Comment by sgiehl** [comment]
does the qr image maybe fail to load?

**Comment by pokrface** [comment]
@sgiehl Thanks for the suggestion to check the chrome console. There was a weird angular.js error there, and when I refreshed to try to see if i could get it to trigger again so I could screenshot it in context........the QR page loaded correctly.

I'll work on trying to repro this if possible, since problems that go away on their own really bother me. If I can get it to retrigger, I'll thoroughly document and reopen this thread.

Sorry for the false alarm!!
