### ISSUE TITLE
Pasword recovery fails when GA plugin activated

### ISSUE THREAD

**Issue by MagicFab** [sgiehl/piwik-plugin-GoogleAuthenticator#3]
When going through password recovery after enabling this 2FA plugin I get the usual email to click on a link and setup a new password. Once I fill the two password fields and submit the information, I get this error:

An error occurred
The plugin Login is not enabled. You can activate the plugin on Settings > Plugins page in Piwik.

**Comment by sgiehl** [comment]
Thanks for the report. I'll have a look at that

**Comment by MagicFab** [comment]
This now works, but also bypasses 2FA :( See issue #4.
