### ISSUE TITLE
Rename from "GoogleAuthenticator"

### ISSUE THREAD

**Issue by Findus23** [sgiehl/piwik-plugin-GoogleAuthenticator#31]
In my opinion this plugin should have a more general name as the login method it implements (TOTP) isn't unique to Google, and we shouldn't advertise for a non-free app when there are hundreds of other (open source) implementations available.

**Comment by sgiehl** [comment]
Closing this, as the plugin will be discontinued as soon as 2FA is integrated in Matomo, which should happen in next release.
