### ISSUE TITLE
Enabling Plugin triggered Array to String Conversion Notice

### ISSUE THREAD

**Issue by jbpyn** [sgiehl/piwik-plugin-GoogleAuthenticator#32]
I received an error message after I enabled the plugin that read: 

"piwik/vendor/twig/twig/lib/Twig/Extension/Core.php(740): Notice - Array to string conversion - Matomo 3.5.1"

Reported to the [matomo forum](https://forum.matomo.org/t/array-to-string-conversion-notice/29028?u=jbpyn). They requested I post it here. Please let me know if you need more information about my setup.

**Comment by sgiehl** [comment]
That seems to be the "join" filter of twig. But as that filter isn't used in this plugin it seems unrelated...
