### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by tsteur** [sgiehl/piwik-plugin-GoogleAuthenticator#36]
@sgiehl could you release a new version so the plugin will be marked as incompatible?

**Comment by sgiehl** [comment]
Already did that a while ago. Latest 3.2.2 was marked as compatible till 3.8.0-b3. See https://github.com/sgiehl/piwik-plugin-GoogleAuthenticator/blob/master/plugin.json#L10

**Comment by tsteur** [comment]
👍  Marketplace didn't show that version but maybe that's actually expected behaviour that it only shows last compatible version https://plugins.matomo.org/GoogleAuthenticator
