### ISSUE TITLE
Piwik broken after activating plugin

### ISSUE THREAD

**Issue by Tralapo** [sgiehl/piwik-plugin-GoogleAuthenticator#7]
I installed Google Authenticator after I saw it in the newsletter Piwik created. Nice plugin. It worked ok for a few days, but now I can't reach Piwik anymore.

When I try to go to my Piwik dashboard, I get a http 500 error. So I took a look at my error log, and saw the following error:

```
PHP Fatal error:  Access level to Piwik\\Plugins\\GoogleAuthenticator\\Controller::$auth must be protected (as in class Piwik\\Plugins\\Login\\Controller) or weaker in /*****/plugins/GoogleAuthenticator/Controller.php on line 24
```

I don't really get this one, what should I change to make Piwik reachable again?

**Comment by sgiehl** [comment]
That is due to a change in latest piwik beta. See piwik/piwik#8681
Try deactivating GoogleAuthenticator in the config until a new version is available

**Comment by Tralapo** [comment]
@sgiehl Thanks, that's working
